kitchen/urls.py
from django.urls import path
from kitchen.views import (
       index,
       DishTypeListView,
       DishTypeCreateView,
       DishTypeUpdateView,
       DishTypeDeleteView,
       DishListView,
       DishDetailView,
       DishCreateView,
       DishUpdateView,
       DishAssignmentView,
       DishDeleteView,
       CookListView,
       CookDetailView,
       CookCreateView,
       CookDeleteView
)

urlpatterns = [
       path("", index, name="index"),
       path("dish-types/", DishTypeListView.as_view(), name="dish-type-list"),
       path("dish-types/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
       path("dish-types/<int:pk>/update/", DishTypeUpdateView.as_view(), name="dish-type-update"),
       path("dish-types/<int:pk>/delete/", DishTypeDeleteView.as_view(), name="dish-type-delete"),
       path("dishes/", DishListView.as_view(), name="dish-list"),
       path("dishes/create/", DishCreateView.as_view(), name="dish-create"),
       path("dishes/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
       path("dishes/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
       path("dishes/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
       path(
              "dishes/<int:pk>/dish-assignment/",
              DishAssignmentView.as_view(),
              name="dish-assignment"),
       path("cooks/", CookListView.as_view(), name="cook-list"),
       path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
       path("cooks/create", CookCreateView.as_view(), name="cook-create"),
       path("cooks/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
]

app_name = "kitchen"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span> <!-- Ліва стрілка -->
        </a>
      </li>
    {% endif %}

    <!-- Кнопки для сторінок -->
    {% for num in page_obj.paginator.page_range %}
      {% if num == page_obj.number %}
        <li class="page-item active">
          <span class="page-link">{{ num }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a href="?{% query_transform request page=num %}" class="page-link">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link" aria-label="Next">
          <span aria-hidden="true">&raquo;</span> <!-- Права стрілка -->
        </a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group list-group-flush">
  <li class="list-group-item bg-transparent border-0 py-2">
    <a href="{% url 'kitchen:index' %}" class="btn btn-primary w-100 text-start text-white fw-bold rounded-pill hover-effect py-3">
      <i class="bi bi-house-door me-2"></i> Home
    </a>
  </li>
  <li class="list-group-item bg-transparent border-0 py-2">
    <a href="{% url 'kitchen:cook-list' %}" class="btn btn-primary w-100 text-start text-white fw-bold rounded-pill hover-effect py-3">
      <i class="bi bi-person-badge me-2"></i> All cooks
    </a>
  </li>
  <li class="list-group-item bg-transparent border-0 py-2">
    <a href="{% url 'kitchen:dish-list' %}" class="btn btn-primary w-100 text-start text-white fw-bold rounded-pill hover-effect py-3">
      <i class="bi bi-egg-fried me-2"></i> All dishes
    </a>
  </li>
  <li class="list-group-item bg-transparent border-0 py-2">
    <a href="{% url 'kitchen:dish-type-list' %}" class="btn btn-primary w-100 text-start text-white fw-bold rounded-pill hover-effect py-3">
      <i class="bi bi-collection me-2"></i> All dish types
    </a>
  </li>
</ul>

templates/includes/username_logout_buttons.html
<!-- Кнопки User і Logout -->
<div class="position-absolute top-0 end-0 mt-3 me-3 d-flex align-items-center">
  {% if user.is_authenticated %}
    <!-- Кнопка Logout -->
    <form method="POST" action="{% url 'logout' %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ request.path }}">
      <button type="submit" class="btn btn-sm bg-white text-primary btn-round me-3 mb-0">Logout</button>
    </form>

    <!-- Кнопка з іменем користувача -->
    <a href="{{ user.get_absolute_url }}" target="_blank"
       class="btn btn-sm bg-white text-primary btn-round mb-0">{{ user.get_username }}</a>
  {% else %}
    <a href="{% url 'login' %}" class="btn btn-link text-white">Login</a>
  {% endif %}
</div>

templates/includes/wave_animation.html
<div class="position-absolute w-100 z-index-1 bottom-0">
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
         viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
        </defs>
        <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
        </g>
    </svg>
</div>